---
title: "Cuquarto Example"
subtitle: Test Cuquarto Revealjs and Beamer theme
author: John Doe
institute: Chulalongkorn University
date: last-modified # today | last-modified
date-format: "MMM YYYY" # see https://momentjs.com/docs/#/displaying/format/
format:
  npquarto-revealjs:
    self-contained: false # set to true to produce a single HTML file
    transition: none # none | fade | slide | convex | concave | zoom
    background-transition: none
  npquarto-beamer:
    aspectratio: 169
    mainfont: Noto Sans Thai
    monofont: Arundina Sans Mono
    mathfont: Kanit
---

# In the morning

## Getting up bullet

- Turn off alarm
- Get out of bed

## A New Slide list

1. Learn R
2. Make webpage

```{r}
#| eval: false
#| echo: true
df <- data.frame(v1 = c(1,2,3),
                v2 = c("a","b","c"))
df
```

# In the evening

## Test Thai

โกเต็กซ์ขั้นตอน รีโมตแคนยอน แทคติคแฟกซ์ แอลมอนด์ เซอร์พรีเมียร์กลาส ไมเกรนโบ้ยรุสโซไฮไลท์ปอดแหก คอร์ปอเรชั่น แฟ้บเป็นไง ศิรินทร์สตรอว์เบอร์รีจิ๊กซอว์ ซาบะวาทกรรม แฮมเบอร์เกอร์กิฟท์ต่อยอด อิมพีเรียลฟลอร์ เซลส์แมน เวณิกาสต็อกอ่อนด้อย สัมนาสตรอเบอร์รีดยุค โปรโมเตอร์อึ๋มวิลเลจ

น้องใหม่ เซนเซอร์ อุปนายิกาน็อกไวอากร้าไนน์นางแบบ ดัมพ์แดนซ์สติกเกอร์ ดีกรี คอนเฟิร์มสไปเดอร์คอนเทนเนอร์เฉิ่ม แบตวาริชศาสตร์ ครัวซองต์ซาร์แทงกั๊กอยุติธรรมเทคโน สแล็กฮัลโลวีนเอาต์เพรส โบรชัวร์ตุ๊ด อัลบั้มโชห่วยเคสพาสเจอร์ไรส์บอมบ์ พริตตี้กิฟท์เคลมเปโซ สติกเกอร์มะกันแฟลชติวเตอร์ เคสแจม ทรูไฮเอนด์เกมส์สลัม สุริยยาตรปอดแหกโมเต็ลฟอร์มอพาร์ทเมนท์

## Test columns

:::: columns
::: {.column width="65%"}
::: {.incremental}
  * This is for less obvious serious problems
  * Method:
    * Get rid of bottom half of your code
    * Problem still exist? 
    * Get rid of bottom half of your code
    * Problem still exist? 
    * etc.. 
:::
:::

::: {.column width="35%"}
  * Surely a second-choice method
  * But sometimes necessary
  * I use this most frequently for R Markdown, which is buggy
:::

::::
